### ISSUE TITLE
Can't build after upgrading to @interchain-ui/react 1.22.15

### ISSUE THREAD

**Issue by Pitasi** [cosmology-tech/interchain-ui#179]
Our React+Vite app no longer builds after upgrading to @interchain-ui/react version 1.22.15.

1.22.14 is working fine.

Here are the build logs:

```
0.729 > vite build
0.729
1.446 vite v5.2.8 building for production...
1.725 transforming...
2.270 ✓ 24 modules transformed.
2.270 x Build failed in 803ms
2.271 error during build:
2.271 CssSyntaxError: [vite:css] [postcss] /wardenprotocol/spaceward/node_modules/.pnpm/@interchain-ui+react@1.22.15_@types+react@18.2.77_react-dom@18.2.0_react@18.2.0/node_modules/@interchain-ui/react/dist/packages/react/src/ui/button/button.css.ts:1:0: `@layer base` is used but no matching `@tailwind base` directive is present.
2.271 file: /wardenprotocol/spaceward/node_modules/.pnpm/@interchain-ui+react@1.22.15_@types+react@18.2.77_react-dom@18.2.0_react@18.2.0/node_modules/@interchain-ui/react/dist/interchain-ui-kit-react.cjs.css:1:-1
2.271     at Input.error (/wardenprotocol/spaceward/node_modules/.pnpm/postcss@8.4.38/node_modules/postcss/lib/input.js:93:16)
2.271     at AtRule.error (/wardenprotocol/spaceward/node_modules/.pnpm/postcss@8.4.38/node_modules/postcss/lib/node.js:115:32)
2.271     at normalizeTailwindDirectives (/wardenprotocol/spaceward/node_modules/.pnpm/tailwindcss@3.4.3/node_modules/tailwindcss/lib/lib/normalizeTailwindDirectives.js:72:32)
2.271     at /wardenprotocol/spaceward/node_modules/.pnpm/tailwindcss@3.4.3/node_modules/tailwindcss/lib/processTailwindFeatures.js:29:98
2.271     at plugins (/wardenprotocol/spaceward/node_modules/.pnpm/tailwindcss@3.4.3/node_modules/tailwindcss/lib/plugin.js:38:69)
2.271     at LazyResult.runOnRoot (/wardenprotocol/spaceward/node_modules/.pnpm/postcss@8.4.38/node_modules/postcss/lib/lazy-result.js:329:16)
2.271     at LazyResult.runAsync (/wardenprotocol/spaceward/node_modules/.pnpm/postcss@8.4.38/node_modules/postcss/lib/lazy-result.js:258:26)
2.271     at LazyResult.async (/wardenprotocol/spaceward/node_modules/.pnpm/postcss@8.4.38/node_modules/postcss/lib/lazy-result.js:160:30)
2.271     at LazyResult.then (/wardenprotocol/spaceward/node_modules/.pnpm/postcss@8.4.38/node_modules/postcss/lib/lazy-result.js:404:17)
2.287  ELIFECYCLE  Command failed with exit code 1.

```

**Comment by yyyyaaa** [comment]
@Pitasi hey I'm closing this one, this issue was solved

**Comment by yyyyaaa** [comment]
still a bit weird as to why tailwind complaining about CSS layers, which should be present in browser baseline

https://web.dev/baseline
